export {
    mockTicketsStats,
    mockTicketMessages,
    mockTicketNotes,
    mockTickets,
    resetTicketsMocks,
    getMockTicketsList,
    getMockUnassignedTickets,
    getMockTicketsStats,
    getMockTicketById,
    createMockTicket,
    updateMockTicket,
    deleteMockTicket,
    assignMockTicket,
    updateMockTicketStatus,
    updateMockTicketPriority,
    getMockMessages,
    sendMockMessage,
    getMockNotes,
    addMockNote,
    deleteMockNote,
} from "./tickets.mock";
