/**
 * CRUD Factory - Type Definitions
 *
 * Generic types for the CRUD factory pattern.
 * These types enable type-safe API and hook generation.
 */

// ============================================================================
// Response Types
// ============================================================================

/**
 * Pagination metadata
 */
export interface PaginationMeta {
    currentPage: number;
    lastPage: number;
    perPage: number;
    total: number;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
    items: T[];
    meta: PaginationMeta;
}

/**
 * Single item response wrapper
 */
export interface SingleResponse<T> {
    data: T;
    message?: string;
}

/**
 * List response type - either paginated or array
 */
export type ListResponse<
    T,
    TPaginated extends boolean = true,
> = TPaginated extends true ? PaginatedResponse<T> : T[];

// ============================================================================
// ID Types
// ============================================================================

/**
 * Valid ID types
 */
export type EntityId = string | number;

/**
 * Extract ID type from entity
 */
export type ExtractId<T, K extends keyof T> = T[K] extends EntityId
    ? T[K]
    : never;

// ============================================================================
// API Configuration
// ============================================================================

/**
 * Configuration for CRUD API factory
 */
export interface CrudApiConfig<
    TEntity,
    TCreatePayload,
    TUpdatePayload,
    TListParams,
> {
    /**
     * Base URL for the API endpoint (e.g., '/api/courses')
     */
    baseUrl: string;

    /**
     * Field name for entity ID (currently informational only)
     * @default 'id'
     * @deprecated Not currently used - ID is always passed explicitly to API methods
     */
    idField?: keyof TEntity;

    /**
     * Use FormData for create/update requests
     * @default false
     */
    useFormData?: boolean;

    /**
     * Transform request payload before sending
     */
    transformRequest?: (
        data: TCreatePayload | TUpdatePayload
    ) => Record<string, unknown>;

    /**
     * Transform response data after receiving
     */
    transformResponse?: (data: unknown) => TEntity;

    /**
     * Transform list response data
     */
    transformListResponse?: (
        data: unknown
    ) => PaginatedResponse<TEntity> | TEntity[];
}

// ============================================================================
// API Interface
// ============================================================================

/**
 * CRUD API interface generated by factory
 */
export interface CrudApi<TEntity, TCreatePayload, TUpdatePayload, TListParams> {
    getList: (
        params?: TListParams,
        signal?: AbortSignal
    ) => Promise<PaginatedResponse<TEntity>>;

    getById: (id: EntityId, signal?: AbortSignal) => Promise<TEntity>;

    create: (payload: TCreatePayload) => Promise<TEntity>;

    update: (id: EntityId, payload: TUpdatePayload) => Promise<TEntity>;

    delete: (id: EntityId) => Promise<void>;
}

// ============================================================================
// Hooks Configuration
// ============================================================================

/**
 * Invalidation strategy options
 */
export type InvalidationStrategy = "list" | "detail" | "all" | "none";

/**
 * Configuration for CRUD hooks factory
 */
export interface CrudHooksConfig<
    TEntity,
    TCreatePayload,
    TUpdatePayload,
    TListParams,
> {
    /**
     * Entity name for query keys (e.g., 'courses')
     */
    entity: string;

    /**
     * CRUD API instance
     */
    api: CrudApi<TEntity, TCreatePayload, TUpdatePayload, TListParams>;

    /**
     * Query key factory
     */
    keys: QueryKeyFactory<string>;

    /**
     * Invalidation strategies for mutations
     */
    invalidation?: {
        onCreate?: InvalidationStrategy;
        onUpdate?: InvalidationStrategy;
        onDelete?: InvalidationStrategy;
    };
}

// ============================================================================
// Query Key Types
// ============================================================================

/**
 * Query key factory interface
 */
export interface QueryKeyFactory<T extends string> {
    all: readonly [T];
    lists: () => readonly [T, "list"];
    list: (
        params?: Record<string, unknown>
    ) => readonly [T, "list"] | readonly [T, "list", Record<string, unknown>];
    infinite: (
        params?: Record<string, unknown>
    ) =>
        | readonly [T, "infinite"]
        | readonly [T, "infinite", Record<string, unknown>];
    details: () => readonly [T, "detail"];
    detail: (id: EntityId) => readonly [T, "detail", EntityId];
}

// ============================================================================
// Hook Return Types
// ============================================================================

/**
 * Update mutation variables
 */
export interface UpdateVariables<TUpdatePayload> {
    id: EntityId;
    data: TUpdatePayload;
}
