import { ChatMessage, ChatUser, ConversationListItem } from "../types";

export const mockConversationListItems: ConversationListItem[] = [
    {
        id: 1,
        type: "private",
        name: "John Doe",
        user: {
            id: 1,
            name: "John Doe",
            role: "Software Engineer",
            avatar: "/images/user/user-01.png",
            status: "online",
            lastSeen: "2024-01-15T10:30:00Z",
        },
        lastMessage: "Hey, how are you doing?",
        lastMessageTime: "10:30 AM",
        unreadCount: 2,
        isPinned: true,
        isMuted: false,
    },
    {
        id: 2,
        type: "private",
        name: "Jane Smith",
        user: {
            id: 2,
            name: "Jane Smith",
            role: "Product Manager",
            avatar: "/images/user/user-02.png",
            status: "offline",
            lastSeen: "2024-01-15T09:00:00Z",
        },
        lastMessage: "The meeting is scheduled for tomorrow",
        lastMessageTime: "Yesterday",
        unreadCount: 0,
        isPinned: false,
        isMuted: false,
    },
    {
        id: 3,
        type: "group",
        name: "Project Team",
        user: {
            id: 3,
            name: "Project Team",
            role: "5 members",
            avatar: "/images/user/user-03.png",
            status: "online",
        },
        lastMessage: "Great work everyone!",
        lastMessageTime: "2 days ago",
        unreadCount: 5,
        isPinned: true,
        isMuted: true,
    },
    {
        id: 4,
        type: "private",
        name: "Mike Johnson",
        user: {
            id: 4,
            name: "Mike Johnson",
            role: "Designer",
            avatar: "/images/user/user-04.png",
            status: "away",
            lastSeen: "2024-01-14T15:45:00Z",
        },
        lastMessage: "Check out the new designs",
        lastMessageTime: "3 days ago",
        unreadCount: 0,
        isPinned: false,
        isMuted: false,
    },
];

export const mockChatMessages: ChatMessage[] = [
    {
        id: 1,
        conversationId: 1,
        senderId: 1,
        sender: {
            id: 1,
            name: "John Doe",
            role: "Software Engineer",
            avatar: "/images/user/user-01.png",
            status: "online",
        },
        type: "text",
        content: "Hey, how are you doing?",
        isRead: true,
        isEdited: false,
        isDeleted: false,
        createdAt: "2024-01-15T10:30:00Z",
        createdAtFormatted: "10:30 AM",
    },
    {
        id: 2,
        conversationId: 1,
        senderId: 2,
        sender: {
            id: 2,
            name: "Jane Smith",
            role: "Product Manager",
            avatar: "/images/user/user-02.png",
            status: "online",
        },
        type: "text",
        content: "I'm doing great! Just finished the project review.",
        isRead: true,
        isEdited: false,
        isDeleted: false,
        createdAt: "2024-01-15T10:32:00Z",
        createdAtFormatted: "10:32 AM",
    },
    {
        id: 3,
        conversationId: 1,
        senderId: 1,
        sender: {
            id: 1,
            name: "John Doe",
            role: "Software Engineer",
            avatar: "/images/user/user-01.png",
            status: "online",
        },
        type: "text",
        content: "That's awesome! Can you share the details?",
        isRead: true,
        isEdited: false,
        isDeleted: false,
        createdAt: "2024-01-15T10:35:00Z",
        createdAtFormatted: "10:35 AM",
    },
    {
        id: 4,
        conversationId: 1,
        senderId: 2,
        sender: {
            id: 2,
            name: "Jane Smith",
            role: "Product Manager",
            avatar: "/images/user/user-02.png",
            status: "online",
        },
        type: "image",
        content: "Here's the screenshot of the dashboard",
        attachments: [
            {
                id: 1,
                type: "image",
                url: "/images/attachments/dashboard.png",
                name: "dashboard.png",
                size: 245000,
            },
        ],
        isRead: false,
        isEdited: false,
        isDeleted: false,
        createdAt: "2024-01-15T10:40:00Z",
        createdAtFormatted: "10:40 AM",
    },
    {
        id: 5,
        conversationId: 1,
        senderId: 1,
        sender: {
            id: 1,
            name: "John Doe",
            role: "Software Engineer",
            avatar: "/images/user/user-01.png",
            status: "online",
        },
        type: "text",
        content: "Looks great! Let's discuss this in our meeting tomorrow.",
        isRead: false,
        isEdited: true,
        isDeleted: false,
        editedAt: "2024-01-15T10:45:30Z",
        createdAt: "2024-01-15T10:45:00Z",
        createdAtFormatted: "10:45 AM",
    },
];

export const mockChatUsers: ChatUser[] = [
    {
        id: 1,
        name: "John Doe",
        role: "Software Engineer",
        avatar: "/images/user/user-01.png",
        status: "online",
        lastSeen: "2024-01-15T10:30:00Z",
    },
    {
        id: 2,
        name: "Jane Smith",
        role: "Product Manager",
        avatar: "/images/user/user-02.png",
        status: "offline",
        lastSeen: "2024-01-15T09:00:00Z",
    },
    {
        id: 3,
        name: "Mike Johnson",
        role: "Designer",
        avatar: "/images/user/user-03.png",
        status: "away",
        lastSeen: "2024-01-14T15:45:00Z",
    },
    {
        id: 4,
        name: "Sarah Williams",
        role: "QA Engineer",
        avatar: "/images/user/user-04.png",
        status: "online",
        lastSeen: "2024-01-15T11:00:00Z",
    },
    {
        id: 5,
        name: "David Brown",
        role: "DevOps Engineer",
        avatar: "/images/user/user-05.png",
        status: "offline",
        lastSeen: "2024-01-14T18:30:00Z",
    },
];
